#!/usr/bin/env python
"""CLI: export a real DexScreener + GoPlus scan as seed data for the web app.

The dashboard in `web/` opens with genuinely scanned tokens rather than
invented ones. This script produces that file; re-run it to refresh.

Example:
    python scripts/export_seed.py --limit 24 --out web/src/data/seedTokens.js
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from meme_scanner.core.filters import ScanFilters, apply_filters  # noqa: E402
from meme_scanner.core.models import TokenPair  # noqa: E402
from meme_scanner.data.dexscreener import DexScreenerClient  # noqa: E402
from meme_scanner.data.goplus import GoPlusClient, SecurityReport  # noqa: E402
from meme_scanner.scanner import EVM_CHAINS  # noqa: E402

DEFAULT_QUERIES = ["solana meme", "pump.fun", "pepe", "dog", "cat", "base meme", "inu", "bonk"]

BANNER = """// Generated by scripts/export_seed.py -- do not edit by hand.
//
// A real scan: market data from DexScreener, security flags from GoPlus
// Security. Re-run the exporter to refresh. Fields GoPlus does not report
// for a given chain are null, and the UI renders those checks as unknown
// rather than passing them.
"""


def dedupe_by_token(pairs: list[TokenPair]) -> list[TokenPair]:
    """Keep the deepest pool per token -- one token trading in five pools
    would otherwise fill the dashboard with near-identical rows."""
    best: dict[str, TokenPair] = {}
    for pair in pairs:
        key = f"{pair.chain_id}:{pair.base_address or pair.base_symbol}"
        if key not in best or pair.liquidity_usd > best[key].liquidity_usd:
            best[key] = pair
    return sorted(best.values(), key=lambda p: p.volume_h24, reverse=True)


def fetch_security(client: GoPlusClient, pair: TokenPair) -> SecurityReport | None:
    if not pair.base_address:
        return None
    try:
        if pair.chain_id == "solana":
            return client.check_solana_token(pair.base_address)
        if pair.chain_id in EVM_CHAINS:
            return client.check_evm_token(pair.chain_id, pair.base_address)
    except Exception as exc:  # a single failed lookup shouldn't sink the export
        print(f"  security lookup failed for {pair.base_symbol}: {exc}", file=sys.stderr)
    return None


def security_to_json(report: SecurityReport | None, chain: str) -> dict:
    if report is None:
        return {
            "checked": False,
            "lpLockedPct": None,
            "buyTaxPct": None,
            "sellTaxPct": None,
            "isHoneypot": None,
            "mintRevoked": None,
            "freezeRevoked": None,
            "top10HoldersPct": None,
            "holderCount": None,
            "isOpenSource": None,
        }

    def pct(value: float | None) -> float | None:
        return None if value is None else round(value, 2)

    def negate(value: bool | None) -> bool | None:
        return None if value is None else not value

    return {
        "checked": True,
        "lpLockedPct": pct(report.lp_locked_pct),
        "buyTaxPct": pct(report.buy_tax_pct),
        "sellTaxPct": pct(report.sell_tax_pct),
        "isHoneypot": report.is_honeypot,
        "mintRevoked": negate(report.is_mintable),
        "freezeRevoked": negate(report.is_freezable),
        "top10HoldersPct": pct(report.top_holder_pct),
        "holderCount": report.holder_count or None,
        "isOpenSource": report.is_open_source,
    }


def pair_to_json(pair: TokenPair, report: SecurityReport | None) -> dict:
    return {
        "id": f"{pair.chain_id}:{pair.pair_address}",
        "chain": pair.chain_id,
        "dex": pair.dex_id,
        "symbol": pair.base_symbol,
        "name": pair.base_name,
        "address": pair.base_address,
        "pairAddress": pair.pair_address,
        "url": pair.url,
        "priceUsd": pair.price_usd,
        "liquidityUsd": round(pair.liquidity_usd, 2),
        "marketCapUsd": round(pair.market_cap or pair.fdv, 2),
        "volumeH24": round(pair.volume_h24, 2),
        "volumeM5": round(pair.volume_m5, 2),
        "txnsM5": {"buys": pair.txns_m5.buys, "sells": pair.txns_m5.sells},
        "txnsH1": {"buys": pair.txns_h1.buys, "sells": pair.txns_h1.sells},
        "priceChangeM5": pair.price_change_m5,
        "priceChangeH1": pair.price_change_h1,
        "priceChangeH24": pair.price_change_h24,
        "ageMinutes": None if pair.age_hours == float("inf") else round(pair.age_hours * 60),
        "source": "live",
        "security": security_to_json(report, pair.chain_id),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Export a real scan as web app seed data")
    parser.add_argument("--query", action="append", dest="queries", default=None)
    parser.add_argument("--chain", action="append", dest="chains", default=None)
    parser.add_argument("--min-liquidity", type=float, default=5000)
    parser.add_argument("--min-volume", type=float, default=1000)
    parser.add_argument("--max-age-hours", type=float, default=24 * 30)
    parser.add_argument("--limit", type=int, default=24)
    parser.add_argument("--out", default="web/src/data/seedTokens.js")
    args = parser.parse_args()

    queries = args.queries or DEFAULT_QUERIES
    filters = ScanFilters(
        chains=args.chains or [],
        min_liquidity_usd=args.min_liquidity,
        min_volume_h24_usd=args.min_volume,
        max_age_hours=args.max_age_hours,
    )

    pairs = apply_filters(DexScreenerClient().scan_queries(queries), filters)
    pairs.sort(key=lambda p: p.volume_h24, reverse=True)
    pairs = dedupe_by_token(pairs)[: args.limit]
    print(f"Scanned {len(pairs)} pairs, running security checks...", file=sys.stderr)

    security_client = GoPlusClient()
    tokens = []
    for pair in pairs:
        report = fetch_security(security_client, pair)
        tokens.append(pair_to_json(pair, report))
        print(f"  {pair.chain_id:10} {pair.base_symbol:12} security={'yes' if report else 'no'}", file=sys.stderr)

    payload = {
        "capturedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "queries": queries,
        "tokens": tokens,
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(BANNER + "\nexport const seedScan = " + json.dumps(payload, indent=2) + ";\n")
    print(f"Wrote {len(tokens)} tokens to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
